version: '3.1'

services:
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8000
    container_name: LaravelApp
    volumes:
      - ./:/var/www/html
    depends_on: 
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: my_project
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage/dbdata:/var/lib/mysql
    ports:
      - 33063:3306


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  db:
